version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - nlp-automation

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - nlp-automation

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - nlp-automation

networks:
  nlp-automation:
    driver: bridge